### ISSUE TITLE
Add ability to search public lists

### ISSUE THREAD

**Issue by jaime-human** [pawap90/uade-movie-app#40]
make users be able to search for public lists. 

@mauro-codes @pawap90 @plaspoumaderes 
Should this be part of the search results section? It could be a third option on the selector that currently holds the 2 options "Peliculas" and "Series"?

**Comment by mauro-codes** [comment]
This feature is not included in the scope of this project

**Comment by jaime-human** [comment]
@mauro-codes  maurooo, in the requirements for the app, the doc has written:

"Las listas publicas pueden ser vistas por cualquier usuario, las privadas solo por los autorizados.".

But im okay if we do not include that, because its not explicit that we should make a search function for lists.

Its your call, you da´ man!
